name: Continuous integration
on: [push]
jobs:
  n0110:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install build-essential imagemagick libfreetype6-dev libjpeg-dev libpng-dev pkg-config
      - uses: numworks/setup-arm-toolchain@2020-q2
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: make -j2 MODEL=n0110 epsilon.dfu
      - run: make -j2 MODEL=n0110 epsilon.onboarding.dfu
      - run: make -j2 MODEL=n0110 epsilon.onboarding.update.dfu
      - run: make -j2 MODEL=n0110 epsilon.onboarding.beta.dfu
      - run: make -j2 MODEL=n0110 flasher.light.dfu
      - run: make -j2 MODEL=n0110 flasher.verbose.dfu
      # We  don't need bench as it is used only in factory
      # - run: make -j2 bench.ram.dfu
      # - run: make -j2 bench.flash.dfu
      - run: make -j2 MODEL=n0110 binpack
      - run: cp output/release/device/n0110/binpack-n0110-`git rev-parse HEAD | head -c 7`.tgz output/release/device/n0110/binpack-n0110.tgz
      - id: 'auth'
        if: ${{ github.event_name == 'push' && github.ref_name == 'upsilon-dev' && github.repository == 'UpsilonNumworks/Upsilon' }}
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{secrets.GOOGLE_CREDENTIALS}}'
      - id: 'upload-directory'
        if: ${{ github.event_name == 'push' && github.ref_name == 'upsilon-dev' && github.repository == 'UpsilonNumworks/Upsilon' }}
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'output/release/device/n0110/binpack/'
          destination: 'upsilon-binfiles.appspot.com/dev/n110/'
          parent: false
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-binpack-n0110.tgz
          path: output/release/device/n0110/binpack-n0110.tgz

env:
  ACCEPT_OFFICIAL_TOS: 1
