name: Continuous integration
on: [push]
jobs:
  n0110:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install build-essential imagemagick libfreetype6-dev libjpeg-dev libpng-dev pkg-config
      - uses: numworks/setup-arm-toolchain@2020-q2
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: make OMEGA_USERNAME="szeroki" -j4
      - run: cp output/release/device/n0110/binpack-n0110-`git rev-parse HEAD | head -c 7`.tgz output/release/device/n0110/binpack-n0110.tgz
      - uses: actions/upload-artifact@v3
      with:
      name: release
      path: output/release/

env:
  ACCEPT_OFFICIAL_TOS: 1
